version: "2.2"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=clouder
      - MYSQL_DATABASE=clouder
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
